
#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/gc?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
  redis:
    host: 127.0.0.1
    port: 6379


#mybatis配置
mybatis-plus:
  type-aliases-package: com.hz.gc.pojo
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印SQL语句


